// dataLoader.js
// RESTORED: loadGameModules
// UPDATED: loadDataForModule now uses manifest.json

export async function loadGameModules() {
  console.log('dataLoader: Starting to load all game modules...');
  try {
      // 1. Fetch the list of active modules
      const moduleList = await fetch('data/module_list.json').then(res => res.json());
      const moduleSystemData = {};

      // 2. Fetch the basic module.json definition for each
      const moduleFetchPromises = moduleList.map(async (moduleId) => {
          const moduleJson = await fetch(`data/modules/${moduleId}/module.json`).then(r => r.json());
          moduleSystemData[moduleId] = moduleJson;
      });

      await Promise.all(moduleFetchPromises);
      console.log('dataLoader: All module definitions loaded successfully.');
      return { moduleSystemData };

  } catch (error) {
      console.error('dataLoader: A critical error occurred while loading module definitions:', error);
      throw error;
  }
}

export async function loadDataForModule(moduleDef) {
  console.log(`dataLoader: Loading all data for module '${moduleDef.id}'...`);
  const moduleId = moduleDef.id;

  try {
      // 1. Load the Manifest (Generated by your Python script)
      const manifest = await fetch(`data/modules/${moduleId}/manifest.json`).then(r => r.json());
      
      // 2. Helper to load a specific category from the manifest
      const loadCategory = async (categoryName) => {
          const fileIds = manifest[categoryName] || [];
          const promises = fileIds.map(id => 
              fetch(`data/modules/${moduleId}/${categoryName}/${id}.json`).then(r => r.json())
          );
          const items = await Promise.all(promises);
          
          // Convert Array of objects to Map { id: object }
          return items.reduce((acc, item) => {
              if (item && item.id) acc[item.id] = item;
              return acc;
          }, {});
      };

      // 3. Load everything in parallel based on keys in the manifest
      const [
          destinies, purposes, nurtures,
          abilities, flaws, perks, 
          bestiary, communities, relationships, items
      ] = await Promise.all([
          loadCategory('destinies'),
          loadCategory('purposes'),
          loadCategory('nurtures'),
          loadCategory('abilities'),
          loadCategory('flaws'),
          loadCategory('perks'),
          loadCategory('bestiary'),
          loadCategory('communities'),
          loadCategory('relationships'),
          loadCategory('items')
      ]);

      console.log(`dataLoader: Module '${moduleId}' loaded.`);

      // 4. Return the data object structure your app expects
      return {
          destinyData: destinies,
          purposeData: purposes,
          nurtureData: nurtures,
          abilityData: abilities,
          flawData: flaws,
          perkData: perks,
          bestiaryData: bestiary,
          communityData: communities,
          relationshipData: relationships,
          equipmentAndLootData: items
      };

  } catch (error) {
      console.error(`Error loading module ${moduleId}:`, error);
      throw error;
  }
}